name: 🐛 Rapport de Bug
description: Signaler un bug ou un comportement inattendu
title: "[BUG] : "
labels: ["bug", "à trier"]
assignees:
  - TheGoatIA

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de remplir ce rapport de bug !
        Plus vous fournirez d'informations, plus vite nous pourrons résoudre le problème.

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug
      placeholder: Décrivez ce qui ne fonctionne pas comme prévu...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire le bug ?
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Faire défiler jusqu'à '...'
        4. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Que devrait-il se passer normalement ?
      placeholder: Décrivez le comportement attendu...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Que se passe-t-il actuellement ?
      placeholder: Décrivez ce qui se passe réellement...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs d'erreur
      description: Copiez et collez les logs d'erreur pertinents
      placeholder: |
        ```
        Collez vos logs ici
        ```
      render: shell

  - type: dropdown
    id: environment
    attributes:
      label: Environnement
      description: Dans quel environnement le bug se produit-il ?
      options:
        - Production
        - Staging
        - Développement
        - Local
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Quelle version de l'API utilisez-vous ?
      placeholder: ex. 1.0.0

  - type: dropdown
    id: severity
    attributes:
      label: Sévérité
      description: Quelle est la gravité du bug ?
      options:
        - Bloquant (empêche l'utilisation)
        - Élevée (impact important)
        - Moyenne (gênant mais contournable)
        - Faible (impact mineur)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexte supplémentaire
      description: Informations supplémentaires qui pourraient être utiles
      placeholder: Screenshots, configuration, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Avant de soumettre, vérifiez que vous avez...
      options:
        - label: Vérifié qu'il n'existe pas déjà une issue similaire
          required: true
        - label: Fourni toutes les informations nécessaires pour reproduire le bug
          required: true
        - label: Testé sur la dernière version
          required: false
