import { v4 as uuidv4 } from 'uuid';

/**
 * Styles prédéfinis à insérer
 */
export const styles = [
    // ========== CYBERPUNK ==========
    {
        styleId: uuidv4(),
        name: 'Cyberpunk',
        nameFr: 'Cyberpunk',
        nameEn: 'Cyberpunk',
        category: 'tech',
        description: 'Neon-drenched cityscapes and futuristic vibes.',
        descriptionFr: 'Paysages urbains baignés de néon et ambiance futuriste.',
        descriptionEn: 'Neon-drenched cityscapes and futuristic vibes.',
        tags: ['cyberpunk', 'futuristic', 'neon', 'tech', 'sci-fi'],
        images: {
            previewUrl: 'https://picsum.photos/seed/cyberpunk/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/cyberpunk/300/200',
            mediumUrl: 'https://picsum.photos/seed/cyberpunk/600/400',
            largeUrl: 'https://picsum.photos/seed/cyberpunk/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'high',
            supportedResolutions: ['1920x1920', '2560x2560', '4096x4096'],
            estimatedProcessingTime: 60,
            requiredMemory: 1536,
            gpuRequired: true,
        },
        pricing: {
            isPremium: true,
            credits: 3,
            tier: 'premium',
        },
        metrics: {
            popularity: 0.92,
            usageCount: 0,
            averageRating: 4.9,
            ratingCount: 0,
            successRate: 0.96,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a cyberpunk style with neon-drenched cityscapes, futuristic elements, and a dark, high-tech atmosphere. Add vibrant neon lights in pink, blue, and purple, holographic displays, rain-slicked streets, and a dystopian urban environment. The subject should be integrated into this cyberpunk world while maintaining their recognizable features.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.9,
                topP: 0.9,
                topK: 60,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== FANTASY ART ==========
    {
        styleId: uuidv4(),
        name: 'Fantasy Art',
        nameFr: 'Art Fantastique',
        nameEn: 'Fantasy Art',
        category: 'artistic',
        description: 'Epic fantasy worlds with magic and wonder.',
        descriptionFr: 'Mondes fantastiques épiques avec magie et émerveillement.',
        descriptionEn: 'Epic fantasy worlds with magic and wonder.',
        tags: ['fantasy', 'magic', 'epic', 'artistic', 'medieval'],
        images: {
            previewUrl: 'https://picsum.photos/seed/fantasy/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/fantasy/300/200',
            mediumUrl: 'https://picsum.photos/seed/fantasy/600/400',
            largeUrl: 'https://picsum.photos/seed/fantasy/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'high',
            supportedResolutions: ['1920x1920', '2560x2560', '4096x4096'],
            estimatedProcessingTime: 55,
            requiredMemory: 1280,
            gpuRequired: true,
        },
        pricing: {
            isPremium: true,
            credits: 3,
            tier: 'premium',
        },
        metrics: {
            popularity: 0.88,
            usageCount: 0,
            averageRating: 4.8,
            ratingCount: 0,
            successRate: 0.94,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into epic fantasy art with magical elements, mystical environments, and a sense of wonder. Add fantasy elements like glowing magical effects, enchanted forests or castles, dramatic lighting, ethereal atmospheres, and a painterly quality. The subject should appear as a fantasy character or be integrated into a magical world.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.85,
                topP: 0.9,
                topK: 55,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== WATERCOLOR ==========
    {
        styleId: uuidv4(),
        name: 'Watercolor',
        nameFr: 'Aquarelle',
        nameEn: 'Watercolor',
        category: 'artistic',
        description: 'Soft, flowing watercolor painting style.',
        descriptionFr: 'Style de peinture aquarelle douce et fluide.',
        descriptionEn: 'Soft, flowing watercolor painting style.',
        tags: ['watercolor', 'art', 'painting', 'soft', 'artistic'],
        images: {
            previewUrl: 'https://picsum.photos/seed/watercolor/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/watercolor/300/200',
            mediumUrl: 'https://picsum.photos/seed/watercolor/600/400',
            largeUrl: 'https://picsum.photos/seed/watercolor/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560', '4096x4096'],
            estimatedProcessingTime: 45,
            requiredMemory: 1024,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.85,
            usageCount: 0,
            averageRating: 4.7,
            ratingCount: 0,
            successRate: 0.95,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a beautiful watercolor painting with soft, flowing brushstrokes, natural color bleeding, and a dreamy, artistic quality. Use delicate washes of color, visible paper texture, gentle gradients, and the characteristic translucent quality of watercolor. Maintain the essence of the subject while giving it an elegant, hand-painted watercolor aesthetic.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.75,
                topP: 0.85,
                topK: 50,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== PIXEL ART ==========
    {
        styleId: uuidv4(),
        name: 'Pixel Art',
        nameFr: 'Pixel Art',
        nameEn: 'Pixel Art',
        category: 'creative',
        description: 'Retro 8-bit and 16-bit pixel art style.',
        descriptionFr: 'Style rétro pixel art 8-bit et 16-bit.',
        descriptionEn: 'Retro 8-bit and 16-bit pixel art style.',
        tags: ['pixel', 'retro', '8bit', '16bit', 'gaming', 'vintage'],
        images: {
            previewUrl: 'https://picsum.photos/seed/pixel/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/pixel/300/200',
            mediumUrl: 'https://picsum.photos/seed/pixel/600/400',
            largeUrl: 'https://picsum.photos/seed/pixel/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 40,
            requiredMemory: 768,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.90,
            usageCount: 0,
            averageRating: 4.8,
            ratingCount: 0,
            successRate: 0.97,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into retro pixel art style with a limited color palette, visible pixels, and a nostalgic 8-bit or 16-bit video game aesthetic. Use dithering effects, hard edges, low resolution charm, and classic gaming vibes. The result should evoke memories of classic video games while maintaining the subject\'s recognizability.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.7,
                topP: 0.85,
                topK: 45,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== PRO HEADSHOT ==========
    {
        styleId: uuidv4(),
        name: 'Pro Headshot',
        nameFr: 'Portrait Professionnel',
        nameEn: 'Pro Headshot',
        category: 'professional',
        description: 'Studio-quality professional headshots.',
        descriptionFr: 'Portraits professionnels de qualité studio.',
        descriptionEn: 'Studio-quality professional headshots.',
        tags: ['professional', 'business', 'corporate', 'linkedin', 'headshot'],
        images: {
            previewUrl: 'https://picsum.photos/seed/headshot/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/headshot/300/200',
            mediumUrl: 'https://picsum.photos/seed/headshot/600/400',
            largeUrl: 'https://picsum.photos/seed/headshot/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 30,
            requiredMemory: 512,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.96,
            usageCount: 0,
            averageRating: 4.9,
            ratingCount: 0,
            successRate: 0.98,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a studio-quality professional headshot suitable for LinkedIn, business cards, and corporate profiles. Enhance lighting with professional studio-style illumination, apply subtle background blur or a clean neutral background, sharpen facial details, improve skin tone naturally, and create a polished, confident, and approachable professional appearance.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.5,
                topP: 0.9,
                topK: 40,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== FILM NOIR ==========
    {
        styleId: uuidv4(),
        name: 'Film Noir',
        nameFr: 'Film Noir',
        nameEn: 'Film Noir',
        category: 'creative',
        description: 'Classic black and white detective movie aesthetic.',
        descriptionFr: 'Esthétique classique des films policiers en noir et blanc.',
        descriptionEn: 'Classic black and white detective movie aesthetic.',
        tags: ['noir', 'detective', 'vintage', 'dramatic', 'blackandwhite'],
        images: {
            previewUrl: 'https://picsum.photos/seed/noir/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/noir/300/200',
            mediumUrl: 'https://picsum.photos/seed/noir/600/400',
            largeUrl: 'https://picsum.photos/seed/noir/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 35,
            requiredMemory: 640,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.82,
            usageCount: 0,
            averageRating: 4.7,
            ratingCount: 0,
            successRate: 0.96,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into classic film noir style with dramatic black and white contrast, venetian blind shadows, moody atmospheric lighting, and a 1940s detective movie aesthetic. Use high contrast, deep shadows, dramatic side lighting, grain texture, and create a mysterious, suspenseful atmosphere reminiscent of classic noir cinema.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.7,
                topP: 0.85,
                topK: 45,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== VINTAGE PHOTO ==========
    {
        styleId: uuidv4(),
        name: 'Vintage Photo',
        nameFr: 'Photo Vintage',
        nameEn: 'Vintage Photo',
        category: 'creative',
        description: 'Nostalgic aged photograph with retro tones.',
        descriptionFr: 'Photographie vieillie nostalgique avec tons rétro.',
        descriptionEn: 'Nostalgic aged photograph with retro tones.',
        tags: ['vintage', 'retro', 'aged', 'nostalgic', 'classic'],
        images: {
            previewUrl: 'https://picsum.photos/seed/vintage/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/vintage/300/200',
            mediumUrl: 'https://picsum.photos/seed/vintage/600/400',
            largeUrl: 'https://picsum.photos/seed/vintage/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'low',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 25,
            requiredMemory: 512,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.87,
            usageCount: 0,
            averageRating: 4.6,
            ratingCount: 0,
            successRate: 0.97,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a nostalgic vintage photograph with aged, retro tones and a classic timeless feel. Add sepia or faded color tones, subtle vignetting, light grain texture, slightly faded appearance, soft focus, and characteristics of old film photography from the 1960s-1980s era. Create a warm, nostalgic atmosphere.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.6,
                topP: 0.8,
                topK: 40,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== PRODUCT SHOT ==========
    {
        styleId: uuidv4(),
        name: 'Product Shot',
        nameFr: 'Photo Produit',
        nameEn: 'Product Shot',
        category: 'professional',
        description: 'Clean commercial product photography style.',
        descriptionFr: 'Style de photographie de produit commercial propre.',
        descriptionEn: 'Clean commercial product photography style.',
        tags: ['product', 'commercial', 'clean', 'professional', 'marketing'],
        images: {
            previewUrl: 'https://picsum.photos/seed/product/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/product/300/200',
            mediumUrl: 'https://picsum.photos/seed/product/600/400',
            largeUrl: 'https://picsum.photos/seed/product/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 30,
            requiredMemory: 640,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.93,
            usageCount: 0,
            averageRating: 4.8,
            ratingCount: 0,
            successRate: 0.98,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a clean, professional commercial product photography style suitable for e-commerce and marketing. Use perfect studio lighting, clean white or subtle gradient background, sharp focus on the subject, enhanced colors and details, professional composition, and create a polished, appealing look that highlights the subject as if it were a premium product.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.5,
                topP: 0.85,
                topK: 40,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== POP ART ==========
    {
        styleId: uuidv4(),
        name: 'Pop Art',
        nameFr: 'Pop Art',
        nameEn: 'Pop Art',
        category: 'artistic',
        description: 'Colorful and bold Pop Art style.',
        descriptionFr: 'Style Pop Art coloré et audacieux.',
        descriptionEn: 'Colorful and bold Pop Art style.',
        tags: ['popart', 'colorful', 'bold', 'artistic', 'retro'],
        images: {
            previewUrl: 'https://picsum.photos/seed/popart/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/popart/300/200',
            mediumUrl: 'https://picsum.photos/seed/popart/600/400',
            largeUrl: 'https://picsum.photos/seed/popart/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 35,
            requiredMemory: 1024,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.80,
            usageCount: 0,
            averageRating: 4.6,
            ratingCount: 0,
            successRate: 0.95,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a Pop Art style masterpiece inspired by Andy Warhol and Roy Lichtenstein. Use bold, vibrant colors, high contrast, comic book-style dots (Ben-Day dots), thick black outlines, and repetitive patterns. Create a striking, graphic look that emphasizes popular culture aesthetics.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.8,
                topP: 0.9,
                topK: 50,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== IMPRESSIONISM ==========
    {
        styleId: uuidv4(),
        name: 'Impressionism',
        nameFr: 'Impressionnisme',
        nameEn: 'Impressionism',
        category: 'artistic',
        description: 'Light and color focused Impressionist style.',
        descriptionFr: 'Style impressionniste axé sur la lumière et la couleur.',
        descriptionEn: 'Light and color focused Impressionist style.',
        tags: ['impressionism', 'art', 'painting', 'light', 'color'],
        images: {
            previewUrl: 'https://picsum.photos/seed/impressionism/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/impressionism/300/200',
            mediumUrl: 'https://picsum.photos/seed/impressionism/600/400',
            largeUrl: 'https://picsum.photos/seed/impressionism/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'high',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 50,
            requiredMemory: 1280,
            gpuRequired: true,
        },
        pricing: {
            isPremium: true,
            credits: 2,
            tier: 'premium',
        },
        metrics: {
            popularity: 0.85,
            usageCount: 0,
            averageRating: 4.8,
            ratingCount: 0,
            successRate: 0.94,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into an Impressionist painting style inspired by Monet and Renoir. Focus on capturing the changing qualities of light, using small, thin, yet visible brush strokes, open composition, and ordinary subject matter. Emphasize the accurate depiction of light in its changing qualities and movement.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.75,
                topP: 0.85,
                topK: 55,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== SURREALISM ==========
    {
        styleId: uuidv4(),
        name: 'Surrealism',
        nameFr: 'Surréalisme',
        nameEn: 'Surrealism',
        category: 'artistic',
        description: 'Dream-like and bizarre Surrealist style.',
        descriptionFr: 'Style surréaliste onirique et bizarre.',
        descriptionEn: 'Dream-like and bizarre Surrealist style.',
        tags: ['surrealism', 'dream', 'bizarre', 'art', 'dali'],
        images: {
            previewUrl: 'https://picsum.photos/seed/surrealism/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/surrealism/300/200',
            mediumUrl: 'https://picsum.photos/seed/surrealism/600/400',
            largeUrl: 'https://picsum.photos/seed/surrealism/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'high',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 60,
            requiredMemory: 1536,
            gpuRequired: true,
        },
        pricing: {
            isPremium: true,
            credits: 3,
            tier: 'premium',
        },
        metrics: {
            popularity: 0.82,
            usageCount: 0,
            averageRating: 4.7,
            ratingCount: 0,
            successRate: 0.92,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a Surrealist artwork inspired by Salvador Dalí and René Magritte. Create a dream-like scene with illogical juxtapositions, melting objects, floating elements, and a sense of the uncanny. Use realistic rendering techniques to depict impossible scenarios and tap into the unconscious mind.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.9,
                topP: 0.95,
                topK: 65,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== STEAMPUNK ==========
    {
        styleId: uuidv4(),
        name: 'Steampunk',
        nameFr: 'Steampunk',
        nameEn: 'Steampunk',
        category: 'tech',
        description: 'Victorian industrial sci-fi aesthetic.',
        descriptionFr: 'Esthétique de science-fiction industrielle victorienne.',
        descriptionEn: 'Victorian industrial sci-fi aesthetic.',
        tags: ['steampunk', 'victorian', 'industrial', 'gears', 'brass'],
        images: {
            previewUrl: 'https://picsum.photos/seed/steampunk/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/steampunk/300/200',
            mediumUrl: 'https://picsum.photos/seed/steampunk/600/400',
            largeUrl: 'https://picsum.photos/seed/steampunk/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'high',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 55,
            requiredMemory: 1280,
            gpuRequired: true,
        },
        pricing: {
            isPremium: true,
            credits: 2,
            tier: 'premium',
        },
        metrics: {
            popularity: 0.88,
            usageCount: 0,
            averageRating: 4.8,
            ratingCount: 0,
            successRate: 0.95,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a Steampunk style with Victorian-era industrial aesthetics. Add brass gears, steam-powered machinery, goggles, leather accessories, and clockwork mechanisms. Use a color palette of sepia, bronze, copper, and leather tones. Create a retro-futuristic atmosphere.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.8,
                topP: 0.9,
                topK: 50,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== SYNTHWAVE ==========
    {
        styleId: uuidv4(),
        name: 'Synthwave',
        nameFr: 'Synthwave',
        nameEn: 'Synthwave',
        category: 'tech',
        description: '80s retro-futuristic neon style.',
        descriptionFr: 'Style néon rétro-futuriste des années 80.',
        descriptionEn: '80s retro-futuristic neon style.',
        tags: ['synthwave', '80s', 'neon', 'retro', 'outrun'],
        images: {
            previewUrl: 'https://picsum.photos/seed/synthwave/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/synthwave/300/200',
            mediumUrl: 'https://picsum.photos/seed/synthwave/600/400',
            largeUrl: 'https://picsum.photos/seed/synthwave/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 40,
            requiredMemory: 1024,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.91,
            usageCount: 0,
            averageRating: 4.7,
            ratingCount: 0,
            successRate: 0.96,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a Synthwave/Outrun style with 80s retro-futuristic aesthetics. Use a color palette of neon pink, purple, and cyan. Add grid lines, sunsets, palm trees silhouettes, and chrome effects. Create a nostalgic yet futuristic vibe reminiscent of 80s sci-fi and arcade games.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.85,
                topP: 0.9,
                topK: 55,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== MINIMALIST ==========
    {
        styleId: uuidv4(),
        name: 'Minimalist',
        nameFr: 'Minimaliste',
        nameEn: 'Minimalist',
        category: 'creative',
        description: 'Clean, simple, and uncluttered style.',
        descriptionFr: 'Style propre, simple et épuré.',
        descriptionEn: 'Clean, simple, and uncluttered style.',
        tags: ['minimalist', 'simple', 'clean', 'modern', 'flat'],
        images: {
            previewUrl: 'https://picsum.photos/seed/minimalist/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/minimalist/300/200',
            mediumUrl: 'https://picsum.photos/seed/minimalist/600/400',
            largeUrl: 'https://picsum.photos/seed/minimalist/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'low',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 25,
            requiredMemory: 512,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.78,
            usageCount: 0,
            averageRating: 4.5,
            ratingCount: 0,
            successRate: 0.98,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a Minimalist style. Simplify shapes, reduce color palette to essential tones, remove unnecessary details and clutter. Focus on negative space, clean lines, and simple composition. Create a modern, elegant, and understated look.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.6,
                topP: 0.8,
                topK: 40,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== ABSTRACT ==========
    {
        styleId: uuidv4(),
        name: 'Abstract',
        nameFr: 'Abstrait',
        nameEn: 'Abstract',
        category: 'artistic',
        description: 'Non-representational artistic style.',
        descriptionFr: 'Style artistique non figuratif.',
        descriptionEn: 'Non-representational artistic style.',
        tags: ['abstract', 'art', 'shapes', 'colors', 'modern'],
        images: {
            previewUrl: 'https://picsum.photos/seed/abstract/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/abstract/300/200',
            mediumUrl: 'https://picsum.photos/seed/abstract/600/400',
            largeUrl: 'https://picsum.photos/seed/abstract/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'high',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 50,
            requiredMemory: 1024,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.75,
            usageCount: 0,
            averageRating: 4.4,
            ratingCount: 0,
            successRate: 0.93,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into an Abstract art style. Focus on shapes, colors, forms, and gestural marks rather than accurate depiction of visual reality. Use bold colors, geometric or organic shapes, and create a composition that evokes emotion through form and color.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.9,
                topP: 0.95,
                topK: 60,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== GRAFFITI ==========
    {
        styleId: uuidv4(),
        name: 'Graffiti',
        nameFr: 'Graffiti',
        nameEn: 'Graffiti',
        category: 'creative',
        description: 'Urban street art style.',
        descriptionFr: 'Style art de rue urbain.',
        descriptionEn: 'Urban street art style.',
        tags: ['graffiti', 'streetart', 'urban', 'spraypaint', 'bold'],
        images: {
            previewUrl: 'https://picsum.photos/seed/graffiti/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/graffiti/300/200',
            mediumUrl: 'https://picsum.photos/seed/graffiti/600/400',
            largeUrl: 'https://picsum.photos/seed/graffiti/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 40,
            requiredMemory: 1024,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.86,
            usageCount: 0,
            averageRating: 4.7,
            ratingCount: 0,
            successRate: 0.96,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a Graffiti street art style. Use vibrant spray paint colors, drip effects, bold outlines, and urban textures like concrete or brick walls. Incorporate tag-style lettering or abstract shapes typical of street art culture.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.85,
                topP: 0.9,
                topK: 55,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== SKETCH ==========
    {
        styleId: uuidv4(),
        name: 'Sketch',
        nameFr: 'Croquis',
        nameEn: 'Sketch',
        category: 'artistic',
        description: 'Hand-drawn pencil sketch style.',
        descriptionFr: 'Style croquis au crayon fait main.',
        descriptionEn: 'Hand-drawn pencil sketch style.',
        tags: ['sketch', 'pencil', 'drawing', 'art', 'monochrome'],
        images: {
            previewUrl: 'https://picsum.photos/seed/sketch/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/sketch/300/200',
            mediumUrl: 'https://picsum.photos/seed/sketch/600/400',
            largeUrl: 'https://picsum.photos/seed/sketch/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'low',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 30,
            requiredMemory: 512,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.89,
            usageCount: 0,
            averageRating: 4.8,
            ratingCount: 0,
            successRate: 0.97,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a hand-drawn pencil Sketch. Use graphite tones, visible pencil strokes, hatching and cross-hatching for shading, and a rough paper texture background. Focus on outlines and shading to create a realistic drawing effect.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.65,
                topP: 0.8,
                topK: 45,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== OIL PAINTING ==========
    {
        styleId: uuidv4(),
        name: 'Oil Painting',
        nameFr: 'Peinture à l\'Huile',
        nameEn: 'Oil Painting',
        category: 'artistic',
        description: 'Classic oil painting style with texture.',
        descriptionFr: 'Style peinture à l\'huile classique avec texture.',
        descriptionEn: 'Classic oil painting style with texture.',
        tags: ['oilpainting', 'art', 'classic', 'texture', 'canvas'],
        images: {
            previewUrl: 'https://picsum.photos/seed/oilpainting/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/oilpainting/300/200',
            mediumUrl: 'https://picsum.photos/seed/oilpainting/600/400',
            largeUrl: 'https://picsum.photos/seed/oilpainting/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'high',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 55,
            requiredMemory: 1280,
            gpuRequired: true,
        },
        pricing: {
            isPremium: true,
            credits: 2,
            tier: 'premium',
        },
        metrics: {
            popularity: 0.87,
            usageCount: 0,
            averageRating: 4.8,
            ratingCount: 0,
            successRate: 0.95,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a classic Oil Painting. Use rich, blended colors, visible brush strokes, canvas texture, and a painterly finish. Emphasize light and shadow, depth, and the traditional techniques of oil painting masters.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.75,
                topP: 0.85,
                topK: 50,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== 3D RENDER ==========
    {
        styleId: uuidv4(),
        name: '3D Render',
        nameFr: 'Rendu 3D',
        nameEn: '3D Render',
        category: 'tech',
        description: 'High-quality CGI 3D rendering style.',
        descriptionFr: 'Style de rendu 3D CGI de haute qualité.',
        descriptionEn: 'High-quality CGI 3D rendering style.',
        tags: ['3d', 'render', 'cgi', 'tech', 'modern'],
        images: {
            previewUrl: 'https://picsum.photos/seed/3drender/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/3drender/300/200',
            mediumUrl: 'https://picsum.photos/seed/3drender/600/400',
            largeUrl: 'https://picsum.photos/seed/3drender/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'high',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 60,
            requiredMemory: 1536,
            gpuRequired: true,
        },
        pricing: {
            isPremium: true,
            credits: 3,
            tier: 'premium',
        },
        metrics: {
            popularity: 0.90,
            usageCount: 0,
            averageRating: 4.9,
            ratingCount: 0,
            successRate: 0.96,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a high-quality 3D Render style. Use physically based rendering (PBR) materials, realistic lighting, soft shadows, and a clean, polished look typical of modern CGI and 3D animation. Give objects a tangible, volumetric feel.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.7,
                topP: 0.9,
                topK: 50,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== ANIME ==========
    {
        styleId: uuidv4(),
        name: 'Anime',
        nameFr: 'Anime',
        nameEn: 'Anime',
        category: 'creative',
        description: 'Japanese animation style.',
        descriptionFr: 'Style d\'animation japonaise.',
        descriptionEn: 'Japanese animation style.',
        tags: ['anime', 'manga', 'japan', 'animation', 'cartoon'],
        images: {
            previewUrl: 'https://picsum.photos/seed/anime/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/anime/300/200',
            mediumUrl: 'https://picsum.photos/seed/anime/600/400',
            largeUrl: 'https://picsum.photos/seed/anime/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 40,
            requiredMemory: 1024,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.94,
            usageCount: 0,
            averageRating: 4.8,
            ratingCount: 0,
            successRate: 0.97,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into an Anime style. Use vibrant colors, expressive character designs, cel-shading, and dynamic compositions typical of modern Japanese animation. Emphasize eyes and hair details, and create a visually striking, animated look.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.8,
                topP: 0.9,
                topK: 55,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== COMIC BOOK ==========
    {
        styleId: uuidv4(),
        name: 'Comic Book',
        nameFr: 'Bande Dessinée',
        nameEn: 'Comic Book',
        category: 'creative',
        description: 'Western comic book style.',
        descriptionFr: 'Style bande dessinée occidentale.',
        descriptionEn: 'Western comic book style.',
        tags: ['comic', 'comicbook', 'illustration', 'bold', 'graphic'],
        images: {
            previewUrl: 'https://picsum.photos/seed/comic/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/comic/300/200',
            mediumUrl: 'https://picsum.photos/seed/comic/600/400',
            largeUrl: 'https://picsum.photos/seed/comic/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 35,
            requiredMemory: 1024,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.88,
            usageCount: 0,
            averageRating: 4.7,
            ratingCount: 0,
            successRate: 0.96,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a Western Comic Book style. Use bold black outlines, dynamic shading, vibrant flat colors, and a graphic novel aesthetic. Emphasize action and drama, and create a visually compelling narrative look.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.75,
                topP: 0.85,
                topK: 50,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },

    // ========== MOSAIC ==========
    {
        styleId: uuidv4(),
        name: 'Mosaic',
        nameFr: 'Mosaïque',
        nameEn: 'Mosaic',
        category: 'artistic',
        description: 'Ancient mosaic tile art style.',
        descriptionFr: 'Style art de tuiles mosaïques anciennes.',
        descriptionEn: 'Ancient mosaic tile art style.',
        tags: ['mosaic', 'tile', 'ancient', 'art', 'pattern'],
        images: {
            previewUrl: 'https://picsum.photos/seed/mosaic/400/400',
            thumbnailUrl: 'https://picsum.photos/seed/mosaic/300/200',
            mediumUrl: 'https://picsum.photos/seed/mosaic/600/400',
            largeUrl: 'https://picsum.photos/seed/mosaic/1200/800',
            exampleTransformations: [],
        },
        technical: {
            modelVersion: 'gemini-2.5-flash-image',
            processingComplexity: 'medium',
            supportedResolutions: ['1920x1920', '2560x2560'],
            estimatedProcessingTime: 45,
            requiredMemory: 1024,
            gpuRequired: false,
        },
        pricing: {
            isPremium: false,
            tier: 'free',
        },
        metrics: {
            popularity: 0.70,
            usageCount: 0,
            averageRating: 4.5,
            ratingCount: 0,
            successRate: 0.94,
        },
        availability: {
            isActive: true,
            regions: ['all'],
            maintenanceMode: false,
        },
        geminiConfig: {
            prompt: 'Transform this image into a Mosaic art style. Compose the image using small, distinct colored tiles (tesserae) separated by grout lines. Create a textured, patterned look reminiscent of ancient Roman or Byzantine mosaics.',
            model: 'gemini-2.5-flash-image',
            parameters: {
                temperature: 0.6,
                topP: 0.8,
                topK: 40,
                maxOutputTokens: 1024,
            },
        },
        createdBy: 'system',
    },
];
